import { Club, Event, RSVP, UserProfile } from '../types';

export const mockUser: UserProfile = {
  id: 'user123',
  name: 'Sarah Johnson',
  email: 'sarah@college.edu',
};

export const mockClubs: Club[] = [
  {
    id: '1',
    name: 'Computer Science Club',
    description: 'Weekly coding workshops and tech talks',
    logo: 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?fm=jpg&fit=crop&w=100&q=40',
    memberCount: 234,
  },
  {
    id: '2',
    name: 'Photography Club',
    description: 'Capture campus moments and learn photography',
    logo: 'https://images.unsplash.com/photo-1518770660439-4636190af475?fm=jpg&fit=crop&w=100&q=40',
    memberCount: 156,
  },
  {
    id: '3',
    name: 'Drama Club',
    description: 'Stage performances and improv workshops',
    logo: 'https://images.unsplash.com/photo-1515165562835-c4c1bfa2b805?fm=jpg&fit=crop&w=100&q=40',
    memberCount: 89,
  },
];

export const mockEvents: Event[] = [
  // Computer Science Club Events
  {
    id: '1',
    clubId: '1',
    title: 'Tech Talk: AI in Modern Development',
    description: 'Explore the latest AI technologies and their applications in software development.',
    date: 'Nov 28, 2025',
    time: '6:00 PM',
    location: 'Engineering Hall 205',
    capacity: 100,
    rsvpCount: 45,
  },
  {
    id: '2',
    clubId: '1',
    title: 'Hack Night: Build a Web App',
    description: 'Team up to build a full-stack web application overnight. Pizza and energy drinks provided!',
    date: 'Dec 5, 2025',
    time: '7:00 PM',
    location: 'Innovation Lab',
    capacity: 50,
    rsvpCount: 40,
  },
  {
    id: '3',
    clubId: '1',
    title: 'Workshop: Introduction to React Native',
    description: 'Learn mobile app development with React Native. Build your first app in this hands-on workshop.',
    date: 'Dec 12, 2025',
    time: '3:00 PM',
    location: 'Computer Lab B',
    capacity: 30,
    rsvpCount: 28,
  },
  {
    id: '4',
    clubId: '1',
    title: 'Career Panel: Tech Industry Insights',
    description: 'Meet alumni working at top tech companies. Learn about career paths and interview tips.',
    date: 'Dec 18, 2025',
    time: '5:00 PM',
    location: 'Engineering Hall 205',
    capacity: 80,
    rsvpCount: 62,
  },
  // Photography Club Events
  {
    id: '5',
    clubId: '2',
    title: 'Golden Hour Photo Walk',
    description: 'Capture stunning sunset photos around campus. All skill levels welcome!',
    date: 'Nov 30, 2025',
    time: '5:00 PM',
    location: 'Campus Quad',
    capacity: 25,
    rsvpCount: 20,
  },
  {
    id: '6',
    clubId: '2',
    title: 'Editing Masterclass: Lightroom Basics',
    description: 'Learn professional photo editing techniques. Bring your laptop with Lightroom installed.',
    date: 'Dec 7, 2025',
    time: '2:00 PM',
    location: 'Media Center',
    capacity: 25,
    rsvpCount: 18,
  },
  {
    id: '7',
    clubId: '2',
    title: 'Portrait Photography Workshop',
    description: 'Master the art of portrait photography with professional lighting and posing techniques.',
    date: 'Dec 14, 2025',
    time: '4:00 PM',
    location: 'Studio A',
    capacity: 20,
    rsvpCount: 15,
  },
  {
    id: '8',
    clubId: '2',
    title: 'Annual Photo Exhibition',
    description: 'Showcase your best work! Submit photos for our end-of-semester exhibition.',
    date: 'Dec 20, 2025',
    time: '6:00 PM',
    location: 'Art Gallery',
    capacity: 100,
    rsvpCount: 45,
  },
  // Drama Club Events
  {
    id: '9',
    clubId: '3',
    title: 'Winter Showcase: Original Skits',
    description: 'Drama club presents an evening of original comedy and drama performances.',
    date: 'Dec 10, 2025',
    time: '6:00 PM',
    location: 'Main Auditorium',
    capacity: 150,
    rsvpCount: 95,
  },
  {
    id: '10',
    clubId: '3',
    title: 'Improv Comedy Night',
    description: 'Laugh out loud with our improv team! Audience participation encouraged.',
    date: 'Nov 29, 2025',
    time: '7:30 PM',
    location: 'Black Box Theater',
    capacity: 60,
    rsvpCount: 52,
  },
  {
    id: '11',
    clubId: '3',
    title: 'Acting Workshop: Method Acting',
    description: 'Learn method acting techniques from a professional theater director.',
    date: 'Dec 3, 2025',
    time: '4:00 PM',
    location: 'Drama Studio',
    capacity: 30,
    rsvpCount: 24,
  },
  {
    id: '12',
    clubId: '3',
    title: 'Shakespeare Reading Circle',
    description: 'Join us for a dramatic reading of Hamlet. All roles open, no experience needed!',
    date: 'Dec 16, 2025',
    time: '5:00 PM',
    location: 'Library Meeting Room',
    capacity: 25,
    rsvpCount: 18,
  },
];

export const mockRsvps: RSVP[] = [
  {
    id: '1',
    userId: mockUser.id,
    eventId: '1',
    userName: mockUser.name,
    email: mockUser.email,
    phone: '9876543210',
    timestamp: '2025-11-15T10:30:00Z',
    attended: false,
  },
];
