import { Club, Event, RSVP, UserProfile } from '../types';

export const mockUser: UserProfile = {
  id: 'user123',
  name: 'Sarah Johnson',
  email: 'sarah@college.edu',
};

export const mockClubs: Club[] = [
  {
    id: '1',
    name: 'Computer Science Club',
    description: 'Weekly coding workshops and tech talks',
    logo: 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?fm=jpg&fit=crop&w=100&q=40',
    category: 'Tech',
    adminId: 'admin1',
    memberCount: 234,
    isVerified: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: '2',
    name: 'Photography Club',
    description: 'Capture campus moments and learn photography',
    logo: 'https://images.unsplash.com/photo-1518770660439-4636190af475?fm=jpg&fit=crop&w=100&q=40',
    category: 'Arts',
    adminId: 'admin1',
    memberCount: 156,
    isVerified: true,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: '3',
    name: 'Drama Club',
    description: 'Stage performances and improv workshops',
    logo: 'https://images.unsplash.com/photo-1515165562835-c4c1bfa2b805?fm=jpg&fit=crop&w=100&q=40',
    category: 'Cultural',
    adminId: 'admin1',
    memberCount: 89,
    isVerified: true,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-11-05'),
  },
];

export const mockEvents: Event[] = [
  // Computer Science Club Events
  {
    id: '1',
    clubId: '1',
    title: 'Tech Talk: AI in Modern Development',
    description: 'Explore the latest AI technologies and their applications in software development.',
    date: '2025-11-28',
    time: '6:00 PM',
    location: 'Engineering Hall 205',
    category: 'Workshop',
    capacity: 100,
    registeredCount: 45,
    status: 'Upcoming',
    registrationRequired: true,
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2025-11-15'),
  },
  {
    id: '2',
    clubId: '1',
    title: 'Hack Night: Build a Web App',
    description: 'Team up to build a full-stack web application overnight. Pizza and energy drinks provided!',
    date: '2025-12-05',
    time: '7:00 PM',
    location: 'Innovation Lab',
    category: 'Competition',
    capacity: 50,
    registeredCount: 40,
    status: 'Upcoming',
    registrationRequired: true,
    createdAt: new Date('2025-11-05'),
    updatedAt: new Date('2025-11-20'),
  },
  {
    id: '3',
    clubId: '1',
    title: 'Workshop: Introduction to React Native',
    description: 'Learn mobile app development with React Native. Build your first app in this hands-on workshop.',
    date: '2025-12-12',
    time: '3:00 PM',
    location: 'Computer Lab B',
    category: 'Workshop',
    capacity: 30,
    registeredCount: 28,
    status: 'Upcoming',
    registrationRequired: true,
    createdAt: new Date('2025-11-10'),
    updatedAt: new Date('2025-11-25'),
  },
  {
    id: '4',
    clubId: '1',
    title: 'Career Panel: Tech Industry Insights',
    description: 'Meet alumni working at top tech companies. Learn about career paths and interview tips.',
    date: '2025-12-18',
    time: '5:00 PM',
    location: 'Engineering Hall 205',
    category: 'Meeting',
    capacity: 80,
    registeredCount: 62,
    status: 'Upcoming',
    registrationRequired: true,
    createdAt: new Date('2025-11-12'),
    updatedAt: new Date('2025-11-28'),
  },
  // Photography Club Events
  {
    id: '5',
    clubId: '2',
    title: 'Golden Hour Photo Walk',
    description: 'Capture stunning sunset photos around campus. All skill levels welcome!',
    date: '2025-11-30',
    time: '5:00 PM',
    location: 'Campus Quad',
    category: 'Social',
    capacity: 25,
    registeredCount: 20,
    status: 'Upcoming',
    registrationRequired: true,
    createdAt: new Date('2025-11-08'),
    updatedAt: new Date('2025-11-22'),
  },
  {
    id: '6',
    clubId: '2',
    title: 'Editing Masterclass: Lightroom Basics',
    description: 'Learn professional photo editing techniques. Bring your laptop with Lightroom installed.',
    date: '2025-12-07',
    time: '2:00 PM',
    location: 'Media Center',
    category: 'Workshop',
    capacity: 25,
    registeredCount: 18,
    status: 'Upcoming',
    registrationRequired: true,
    createdAt: new Date('2025-11-10'),
    updatedAt: new Date('2025-11-25'),
  },
  {
    id: '7',
    clubId: '2',
    title: 'Portrait Photography Workshop',
    description: 'Master the art of portrait photography with professional lighting and posing techniques.',
    date: '2025-12-14',
    time: '4:00 PM',
    location: 'Studio A',
    category: 'Workshop',
    capacity: 20,
    registeredCount: 15,
    status: 'Upcoming',
    registrationRequired: true,
    createdAt: new Date('2025-11-12'),
    updatedAt: new Date('2025-11-28'),
  },
  {
    id: '8',
    clubId: '2',
    title: 'Annual Photo Exhibition',
    description: 'Showcase your best work! Submit photos for our end-of-semester exhibition.',
    date: '2025-12-20',
    time: '6:00 PM',
    location: 'Art Gallery',
    category: 'Social',
    capacity: 100,
    registeredCount: 45,
    status: 'Upcoming',
    registrationRequired: true,
    createdAt: new Date('2025-11-15'),
    updatedAt: new Date('2025-12-01'),
  },
  // Drama Club Events
  {
    id: '9',
    clubId: '3',
    title: 'Winter Showcase: Original Skits',
    description: 'Drama club presents an evening of original comedy and drama performances.',
    date: '2025-12-10',
    time: '6:00 PM',
    location: 'Main Auditorium',
    category: 'Social',
    capacity: 150,
    registeredCount: 95,
    status: 'Upcoming',
    registrationRequired: true,
    createdAt: new Date('2025-11-05'),
    updatedAt: new Date('2025-11-20'),
  },
  {
    id: '10',
    clubId: '3',
    title: 'Improv Comedy Night',
    description: 'Laugh out loud with our improv team! Audience participation encouraged.',
    date: '2025-11-29',
    time: '7:30 PM',
    location: 'Black Box Theater',
    category: 'Social',
    capacity: 60,
    registeredCount: 52,
    status: 'Upcoming',
    registrationRequired: true,
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2025-11-15'),
  },
  {
    id: '11',
    clubId: '3',
    title: 'Acting Workshop: Method Acting',
    description: 'Learn method acting techniques from a professional theater director.',
    date: '2025-12-03',
    time: '4:00 PM',
    location: 'Drama Studio',
    category: 'Workshop',
    capacity: 30,
    registeredCount: 24,
    status: 'Upcoming',
    registrationRequired: true,
    createdAt: new Date('2025-11-08'),
    updatedAt: new Date('2025-11-22'),
  },
  {
    id: '12',
    clubId: '3',
    title: 'Shakespeare Reading Circle',
    description: 'Join us for a dramatic reading of Hamlet. All roles open, no experience needed!',
    date: '2025-12-16',
    time: '5:00 PM',
    location: 'Library Meeting Room',
    category: 'Meeting',
    capacity: 25,
    registeredCount: 18,
    status: 'Upcoming',
    registrationRequired: true,
    createdAt: new Date('2025-11-12'),
    updatedAt: new Date('2025-11-28'),
  },
];

export const mockRsvps: RSVP[] = [
  {
    id: '1',
    userId: mockUser.id,
    eventId: '1',
    userName: mockUser.name,
    email: mockUser.email,
    phone: '9876543210',
    timestamp: '2025-11-15T10:30:00Z',
    attended: false,
  },
];
